services:
  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  backend:
    build:
      dockerfile: /Dockerfile
    image: cleanarchitecture:v1
    container_name: Backend
    command: 
    ports:
      - 8081:8080
    depends_on:
      - database
 
