@Restaurants.API_HostAddress = http://localhost:8081/api
@Identity = http://localhost:8081/api/identity
@Token = CfDJ8DWE0OeNfEZLjMZxGPilwqUc7FcxsZdna5VQslrwrPZDjaLe_ViQ4d7RtvtNRkTKJFoxB7Q_4w8IWRZIJc1lUHA5EcJ1nMbe7V1Ud_7ElTy8DiXmg8Jl70zUXs8H_ukgpkif8uWm9F3Txzow3EamTeMkpGZsUKiiLgL2TF8o0cbLYVa4WX4MBhveQKcamQ9_xUbEEUaMO9IMJhct3aDY5i_QI96b9OnQSLMlHVMciioFO9FNe2P3JUu-88Unffj2Nl9Bw9KZ61paNkmU6DSje_Y88yUBbmVRACHz_r2SZNqjSvfGc1mvYAMBX20YKHm4PL3UdMiYY49uhAV-2_BaJ_swDXdYzGh_Yox_MwmL728W0QTt5ICdQKtAVHY269onTt20SGFrEEBqxi81pjzyE5og3BNOEfilJZp5URmJ1FiVyRSy_HshIOlDzX1Uo73ENIN2Q6cn1JtrcbH1AoI64OvKeUptP7wZF6n7q1Mlmm-wwVi3rKhz7g6YLYgi9VlBEff5v95PLMfCc4RsFLHJ6hRl9uesnmCOpCxw9X7Rw4Ll-izKlsaj_2BUltM5ljjzlXdpHk-FaSC1WiRyZD_clJiLYoGhls5VCw64bOGVy3AeoYg7KRMy7oOVSKQX2zT-4gGfCPcZd1_M04J9D6uOHxokGqLDSwWLxdktAFv7zFNSW_B0GNHq1uS7EIj2nrEuYg
GET {{Restaurants.API_HostAddress}}/Restaurants?serachPhraze=&pageSize=20&pagenumber=3
Accept: application/json
Authorization: Bearer {{Token}}

###
GET {{Restaurants.API_HostAddress}}/Restaurants/9991
Accept: application/json
###
POST {{Restaurants.API_HostAddress}}/Restaurants
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "Name":"Spicy Delights",
  "Description": "A culinary experience like no other",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@gmail.com",
  "Contactnumber": "555-123,4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "12-554"
}

###
DELETE {{Restaurants.API_HostAddress}}/Restaurants/4
Accept: application/json
###
PATCH {{Restaurants.API_HostAddress}}/Restaurants/4
Content-Type: application/json

{
  "Name":"Test Sample",
  "Description": "A culinary experience like no other",
  "Category": "Italian",
  "HasDelivery": false
  
}
###
POST {{Restaurants.API_HostAddress}}/restaurants/2/Dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 23,
  "KiloCalories": 20
}
###
GET {{Restaurants.API_HostAddress}}/restaurants/1/Dishes
Accept: application/json
###
GET {{Restaurants.API_HostAddress}}/restaurants/2/Dishes/2
Accept: application/json
###
DELETE {{Restaurants.API_HostAddress}}/restaurants/2/Dishes/9
###
POST {{Identity}}/register
Content-Type: application/json

{
  "email": "bigOwner@test.com",
  "password": "Password1!"
}
###

POST {{Identity}}/login
Content-Type: application/json

{
  "email": "bigOwner@test.com",
  "password": "Password1!"
}
