@Restaurants.API_HostAddress = http://localhost:5045/api
@Identity = http://localhost:5045/api/identity
@Token = CfDJ8MIocOv7nbdKlPmz1JrFYogXn30Bxz1gCBRvYT1VfQ7N9tNk6B58mH8Sxwx0PpOIiKY8w5awUNycSBXfKHfyVcWTXWOoKH9e3yrGJTa_32u0SqCvUtNsVL9PPincYsrBt1TuS0sKNtXRpn0CNZhJQJpl3yOA24tyzmbPvwOXYk5bD5Y0Ym3kwvukQhssIXcY8OYzLFJRi9p3fdOTdD5q9nWwzS24BeN7WwStf8oA1-R9aEI5jInhXmwk79l-Sg39uYrHIM-rF2AmBDrYdKAtfY4xu_0zYvivkSwkhla9HKGN8WRrkvm93cxmKwEpBbwYNP_VRspFhwEa9jsc1MQM3x2HhvZD8alEGOlGmOTNTkCKpGZuWtr5XAOXdLUFJdRjz9enMGdf0NvZeUWi_L4InpjZ3CkkZqZFTAPtqrRPYcDOc_F0HSWFinnZ8pDKeIxVC4-GLV3Pnwdh3DXIg8qqrD1whE-cVvSmqdxLK2nAMOFoJ-eh1ID_vcxvQHHNysgGazhDBUkuuMqhrXGajNxGweb1jlWkJoXp5X8TfBbzCa1neJ42hkVOYLFJCk0GYEybAeAyfCEGIW3M5-iw8fwNHPnp1IjwdISEYTzaN-xgZI3IcLHLVwsxDm_cTOre3fxNo41vwg7uWNMnKL08Wbhk_Y14E2HsqlFYBmt-jFn1lZg9celQ3RYUh9YZHDc5fSpz3A
GET {{Restaurants.API_HostAddress}}/Restaurants
Accept: application/json
Authorization: Bearer {{Token}}

###
GET {{Restaurants.API_HostAddress}}/Restaurants/2
Accept: application/json
###
POST {{Restaurants.API_HostAddress}}/Restaurants
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "Name":"Spicy Delights",
  "Description": "A culinary experience like no other",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@gmail.com",
  "Contactnumber": "555-123,4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "12-554"
}

###
DELETE {{Restaurants.API_HostAddress}}/Restaurants/4
Accept: application/json
###
PATCH {{Restaurants.API_HostAddress}}/Restaurants/4
Content-Type: application/json

{
  "Name":"Test Sample",
  "Description": "A culinary experience like no other",
  "Category": "Italian",
  "HasDelivery": false
  
}
###
POST {{Restaurants.API_HostAddress}}/restaurants/2/Dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 23,
  "KiloCalories": 20
}
###
GET {{Restaurants.API_HostAddress}}/restaurants/1/Dishes
Accept: application/json
###
GET {{Restaurants.API_HostAddress}}/restaurants/2/Dishes/2
Accept: application/json
###
DELETE {{Restaurants.API_HostAddress}}/restaurants/2/Dishes/9
###
POST {{Identity}}/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Password1!"
}
###

POST {{Identity}}/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}
