@Restaurants.API_HostAddress = http://localhost:5045/api
@Identity = http://localhost:5045/api/identity
@Token = CfDJ8MIocOv7nbdKlPmz1JrFYoh2TGYOKEpAV1HeF2RQgVRpmB5OVzeA9daHnjZtolHjPb08-vZ9waYHxlNrutC_U8Yy_ImJWPmBlwg4NGe6EgVVT5FDb7vWM57uCbiHg5zkU3oHCpmR5fC03blHXs6P8SF30KA0axcJJvfSVxUjNo9LtVKceYUKDREVhlrov2Ut05k7bWRZdVAsIgWcNo-QYEH6zW_ud1IFKBNehKMuGUgKJP9TMRnv-rnM_YEPp41wGBeSxTPDXDGos8irqytI8p5KpYHKEqG9ISm5kiI81acSwRAp-QlpVMOtogLM6usGthsykTZfwQMao9KVOeQcH8D_G8n6KTTX4TNlPJjHtLBrg_wfpS7YjYGU9OksOAfWqQzeLDCkuYbJtSITp99hpZFirya8TkmUmZZINYQTwfBFLY8anCgjAU-OCPk4iRJaDbETT7G7WPEw_4_FLEZBZlDWdAGr1kD9Rv53t4eg86c9Qmz66BdqFhN-7UQFyKWIEkr7L9W5xU5nZCCa1mcitXGzNFduDvYNgwDCdc37N-8UIojMUWcVPWyCGLe1dKO3-z6dTzWvtxWN3bW2Eqd9_BAJq5ISUaPbFTmMAPcXCqinrTQEM9fgB0vU4vHO_EqC6cMUedmP2mJIJWDSvsSIp4X6oT8KZZyirdWH53iTMfr4uGBNEYwcXEpqRqH5r7Yavw
GET {{Restaurants.API_HostAddress}}/Restaurants
Accept: application/json
Authorization: Bearer {{Token}}

###
GET {{Restaurants.API_HostAddress}}/Restaurants/2
Accept: application/json
###
POST {{Restaurants.API_HostAddress}}/Restaurants
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "Name":"Spicy Delights",
  "Description": "A culinary experience like no other",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@gmail.com",
  "Contactnumber": "555-123,4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "12-554"
}

###
DELETE {{Restaurants.API_HostAddress}}/Restaurants/4
Accept: application/json
###
PATCH {{Restaurants.API_HostAddress}}/Restaurants/4
Content-Type: application/json

{
  "Name":"Test Sample",
  "Description": "A culinary experience like no other",
  "Category": "Italian",
  "HasDelivery": false
  
}
###
POST {{Restaurants.API_HostAddress}}/restaurants/2/Dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 23,
  "KiloCalories": 20
}
###
GET {{Restaurants.API_HostAddress}}/restaurants/1/Dishes
Accept: application/json
###
GET {{Restaurants.API_HostAddress}}/restaurants/2/Dishes/2
Accept: application/json
###
DELETE {{Restaurants.API_HostAddress}}/restaurants/2/Dishes/9
###
POST {{Identity}}/register
Content-Type: application/json

{
  "email": "bigOwner@test.com",
  "password": "Password1!"
}
###

POST {{Identity}}/login
Content-Type: application/json

{
  "email": "bigOwner@test.com",
  "password": "Password1!"
}
